# Generated by Django 3.2.7 on 2021-09-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210918_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userr',
            new_name='User',
        ),
    ]
