# Generated by Django 3.2.7 on 2021-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210918_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addressA',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='addressB',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
